name: Matrix Demo # run jobs with help of the matrix, run job with different configurations
on: push

jobs:
    build:
        strategy: # run jobs multiple times once per value in config - all combinations
          matrix:
            node-version: [12, 14, 16]
            operating-system: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependecies
              run: npm ci
            - name: Build Project
              run: npm run build
            